name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - run: echo "******** MAIN ACTION ********"
      - run: echo README.md
