name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}    
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - run: echo "******** MAIN ACTION ********"
      - run: cat README.md

#      - run: sudo apt-get update
#      - run: sudo apt-get install texlive-full

#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          activate-environment: CDIS
#          environment-file: environment.yml
#      - run: conda info
#      - run: conda list
#      - run: conda config --show

#      - run: echo "dummy change (check no history in gh-pages)"
#      - run: pandoc -v > pandoc.v.txt

      - run: echo "stuff" > stuff.txt


      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true